### ISSUE TITLE
Feature: local path

### ISSUE THREAD

**Issue by ursbraem** [dingjie/atom-sync#18]
Using popular build scripts (like the one that comes with foundation 6), there is a /dist/ folder that contains the entire produced site and is purged at each compilation.

Now I would like to sync `local/dist` directly to `remote/public_html`.

The logical way would be to put the `.sync-config.cson` into `local/dist`.
But I can't do that, as the build script deletes `local/dist` all the time.

A solution would be that you can't only place the cson in the targetted directory, but also specify a path you want to sync.

```
remote:
  host: "server"
  user: "username"
  path: "/home/user/public_html/"
local:
  path: "/dist"
```

What do you think?
